services:
  client:
    build: ./client
    ports:
      - "5173:80"
    restart: always
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - sqlite_data:/data
      - uploads:/data/uploads
    restart: always
    env_file:
      - ./server/.env

volumes:
  sqlite_data:
  uploads:
